### PR TITLE
Adding/updating crypto benchmarks

### PR DESCRIPTION
**Pull request by jerrylui803**
Signed-off-by: Jerry Lui  jerrylui803@gmail.com

### CODE REVIEW

**Comment by sehirst** [comment]
Jerry works with me and we worked together on this. Please add me as a reviewer for the PR.

**Comment by sehirst** [comment]
@jerrylui803 Please add a bit more description in your commit message. There should be a subject followed by a blank line, and then the rest of the description. Just enough to explain why this commit is happening and what the code is used for. A few sentences should be enough.

**Comment by karianna** [comment]
@sehirst - I've sent you an invite to the testing team

**Review by sehirst — APPROVED** [review]

**Comment by sehirst** [comment]
This change is updating some existing crypto perf benchmarks and adding others that we have been using for a while now with an outdated version of bumblebench. Changes are LGTM.

**Pull request merged**
